### ISSUE TITLE
首頁圖片被切到一點

### ISSUE THREAD

**Issue by moogoo78** [TaiBIF/portal20#22]
<img width="1176" alt="截圖 2020-03-30 下午4 37 00" src="https://user-images.githubusercontent.com/428769/77892644-841ec200-72a5-11ea-92a3-0fec013f96fb.png">

下面的專題文章也是

**Comment by v02202** [comment]
是指最後一行字的下面嗎？（像是第一個圖的“申請中”）

**Comment by moogoo78** [comment]
> 是指最後一行字的下面嗎？（像是第一個圖的“申請中”）

對 沒錯 !

**Comment by moogoo78** [comment]
fixed https://github.com/TaiBIF/portal20/commit/842ae01e2362d826628c4c2682fb5d49f07b03d7
