### ISSUE TITLE
首頁下方夥伴單位跟指導單位的 logo 解析度太低

### ISSUE THREAD

**Issue by moogoo78** [TaiBIF/portal20#23]

**Comment by v02202** [comment]
已下載解析度較高的logo待裁切

**Comment by melissa0520** [comment]
是否已裁切完畢？沒有的話我這邊可以裁切（能提供需要的大小給我更好）

**Comment by v02202** [comment]
> @v02202 是否已裁切完畢？沒有的話我這邊可以裁切（能提供需要的大小給我更好）

還沒裁切，麻煩你裁178 × 80的尺寸，謝謝你
