### ISSUE TITLE
英文版

### ISSUE THREAD

**Issue by moogoo78** [TaiBIF/portal20#51]

**Comment by melissa0520** [comment]
主選單

- 資料開放 **Open data**
1.  Open data 概述 **About open data**
2. 資料發布狀況 **Data publishing status**
3. 資料上傳 **Publish your data**
4. 資料論文/期刊 **Data paper/Journal**

- 工具與文件 **Tools & Doc**
1. 工具分享 **Data check tools**
2. Cookbook

- 關於TaiBIF **About TaiBIF**
1. TaiBIF簡介 **About us**
2. GBIF介紹 **About GBIF**
3. 聯絡我們 **Contacts**
4. 相關連結 **Databases & Links**

- 更多資訊 **More Info**
1. 最新消息 **Latest news**
(1) 新聞 **News**
(2)活動 **Activities & events**
(3)更新 **TaiCoL checklist updates**
2. 專題文章 **Theme articles**
(1) 科普文章 **Popular science**
(2) 技術專欄 **Technical column**
(3) 出版品資料 **Publications**
(4) TaiBIF 發表文章/海報  **TaiBIF academic publications**

**Comment by melissa0520** [comment]
首頁標語：TaiBIF-生物多樣性資料開放的推手 **TaiBIF- The facilitator of biodiversity open data**

首頁搜尋

- 出現紀錄 **Occurrences**
- 物種 **Species**
- 資料集 **Datasets**
- 發布者 **Publishers**
- 全站搜尋 **Site search**
