### ISSUE TITLE
物種搜尋結果有bug

### ISSUE THREAD

**Issue by szyitsai** [TaiBIF/portal20#76]
http://portal.taibif.tw/species/search/?q=黃尾鴝&rank=species

1. 物種頁點不進去，Server Error 500
2. 物種學名只有種小名，但理論上要加上屬名
3. 搜尋很慢...以為是壞掉orz
4. 點進去屬名、科名的同物異名欄都是台灣穗花杉的學名...

**Comment by moogoo78** [comment]
fixed
